version: "3"
services:
  react:
    image: "mcr.microsoft.com/vscode/devcontainers/typescript-node:0-18-bullseye"
    working_dir: /workspace
    volumes:
      # node_modulesディレクトリはホスト側に渡さないようにDockerのvolume内に格納します
      # - node-modules:/workspace/node_modules
      - .:/workspace:cached
    ports:
      - 3000:3000
    tty: true
