version: "3"
services:
  next:
    image: "mcr.microsoft.com/vscode/devcontainers/typescript-node:0-18-bullseye"
    # image: mcr.microsoft.com/vscode/devcontainers/javascript-node:0-14
    # working_dirディレクトリ下にホストのディレクトリをマウントします
    working_dir: /workspace
    volumes:
      # node_modulesディレクトリはホスト側に渡さないようにDockerのvolume内に格納します
      # - node-modules:/workspace/node_modules
      - .:/workspace:cached
    # コンテナを起動させ続ける
    ports:
      - 3000:3000
      - 6006:6006
    tty: true
    networks:
      - graphqlstack
networks:
  graphqlstack:
    driver: bridge
    name: graphqlstack-network
